repositories:
  - id: standards-lab
    url: https://github.com/OpenDataServices/standards-lab
    branches:
        - main
    app_name_format: standards-lab
    # Commands to set up this app:
    # See https://standards-lab.readthedocs.io/en/latest/admin/dokku.html