global:
  scrape_interval: 60s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 60s
    static_configs:
      - targets: ['localhost:9057']
    scheme: http
  - job_name: 'own_node_exporter'
    scrape_interval: 60s
    static_configs:
      - targets: ['localhost:9157']
    scheme: http
  - job_name: 'live4'
    scrape_interval: 60s
    static_configs:
      - targets: ['prom-client.live4.default.opendataservices.uk0.bigv.io']
    scheme: http
    basic_auth:
      username: prom
      password: {{ pillar.prometheus.client_password }}

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - 'localhost:9095'

rule_files:
  - /home/{{ user }}/conf-prometheus-rules.yml

