ANNOTATEIT_KEY = ''
ANNOTATEIT_SECRET = ''
DB_PASSWORD = '{{ pillar[repo].mysql_password }}'
GITHUB_API_CLIENT_ID = ''
GITHUB_API_CLIENT_SECRET = ''
SECRET_KEY = '{{ pillar[repo].secret_key }}'
SENDGRID_PASSWORD = ''
SENDGRID_USERNAME = ''
SITE_UNIQUE_ID = ''

