pwyf_merger:
  site_url: 'pwyf-merger'
  servername: 'activitymergetool.publishwhatyoufund.org'
  checkout_dir: 'activity-merge-tool'
  git_url: 'https://github.com/pwyf/iati-activity-merger'
  branch: 'master'
  user: 'merger'
  static_dir: '/var/www/static/'
  input_dir: '/var/www/input/'
  output_dir: '/var/www/output/'
